### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by zapplebee** [rv-kip/express-redis-cache#106]
Looking at the PRs (specifically https://github.com/rv-kip/express-redis-cache/pull/93), there are good features and fixes that should be merged. But there's been no dialog or movement?

Is there a need for more maintainers?

**Comment by rv-kip** [comment]
Definitely not abandoned. I'm quite busy and would gladly accept some help going through these pull requests.

**Comment by knoxcard** [comment]
@co2-git, @rv-kip Have you appointed other contributors as collaborators?

I know it's hard handing over the keys, but we all win in the end.  I've seen numerous awesome repos turn into slow moving behemoths.

Things can always be reverted and fixed with versioning.
Here is how to do it, just providing all the info and personal perspective, just in case it's helpful.

https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by rv-kip** [comment]
I am quite open to collaborators. I welcome anyone who wants to help. I'm very busy with the day job.

**Comment by krazyjakee** [comment]
I would be happy to collaborate. We are about to test this for use with a large-scale application but need one essential feature (#110).

My first action would be to clean up issues and pull requests, then after some time is given for responses from the contributors, modernize the code with ES6 classes and finally implement the tagging feature. From there I will continue to offer support.

**Comment by krazyjakee** [comment]
Ok, check the dev branch.

**Comment by rawpixel-vincent** [comment]
Hello, 3 years later :), here to offer some helps as well, very happy with @krazyjakee and others efforts on the dev branch and would like to help give the last push towards a new release.
